In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'pandas'

In [ ]:
df1= pd.read_csv('/content/loan_risk_prediction_dataset.csv')

In [ ]:
df1.head()

,text,protein,carbs,fat,fiber,sugar,sodium,calories,health_class,nutrition_labels
0,134g almonds,28.21,29.55,65.82,16.79,2.73,1.34,823.42,Unhealthy,High Fat|High Fiber|High Protein|Low Sodium|Lo...
1,"140g beans cooked, 198g banana, 135g chicken b...",56.45,77.71,6.14,13.53,20.09,104.31,591.90,Balanced,High Carb|High Fiber|High Protein|High Sugar|L...
2,"164g cheese cheddar, 186g tomato",42.75,9.39,54.59,2.23,9.63,1029.55,699.87,Unhealthy,High Fat|High Protein|High Sodium|Low Carb
3,"177g chicken breast, 94g apple",55.00,13.22,6.54,2.27,7.25,131.57,331.74,Balanced,High Protein|Low Carb|Low Fat|Low Sodium
4,"151g lentils cooked, 170g banana",15.47,69.26,1.11,16.50,7.46,4.72,348.91,Balanced,High Fiber|Low Fat|Low Sodium

In [ ]:
df2.head()

,Food_Item,calories,protein,carbs,fat,fiber,sugar,sodium,Default_Weight,Aliases,nutrition_profile
0,chicken breast,144.4,28.0,0.0,3.6,0.0,0.0,74.0,100,"chicken, poultry, breast, white meat",High Protein|Low Carb|Low Fat|Low Fiber|Low So...
1,beef (lean),239.0,26.0,0.0,15.0,0.0,0.0,72.0,100,"meat, beef, steak, red meat, cow",High Protein|Low Carb|Low Fiber|Low Sodium|Low...
2,salmon,205.0,22.0,0.0,13.0,0.0,0.0,60.0,100,"fish, salmon, seafood, pink fish",Low Carb|Low Fiber|Low Sodium|Low Sugar
3,eggs,138.7,12.6,0.7,9.5,0.0,0.4,124.0,100,"egg, eggs, boiled egg, fried egg, protein source",Low Carb|Low Fat|Low Fiber|Low Sodium|Low Sugar
4,tofu,82.8,8.0,1.9,4.8,0.3,0.7,7.0,100,"tofu, bean curd, soy protein, vegan meat",Low Carb|Low Fat|Low Fiber|Low Protein|Low Sod...